create table if not exists store (
        s_store_sk integer not null,
        s_store_id char(16) not null,
        s_rec_start_date date,
        s_rec_end_date date,
        s_closed_date_sk integer,
        s_store_name varchar(50),
        s_number_employees integer,
        s_floor_space integer,
        s_hours char(20),
        s_manager varchar(40),
        s_market_id integer,
        s_geography_class varchar(100),
        s_market_desc varchar(100),
        s_market_manager varchar(40),
        s_division_id integer,
        s_division_name varchar(50),
        s_company_id integer,
        s_company_name varchar(50),
        s_street_number varchar(10),
        s_street_name varchar(60),
        s_street_type char(15),
        s_suite_number char(10),
        s_city varchar(60),
        s_county varchar(30),
        s_state char(2),
        s_zip char(10),
        s_country varchar(20),
        s_gmt_offset decimal(5,2),
        s_tax_percentage decimal(5,2),
        primary key (s_store_sk)
 );

create table if not exists customer (
        c_customer_sk integer not null,
        c_customer_id char(16) not null,
        c_current_cdemo_sk integer,
        c_current_hdemo_sk integer,
        c_current_addr_sk integer,
        c_first_shipto_date_sk integer,
        c_first_sales_date_sk integer,
        c_salutation char(10),
        c_first_name char(20),
        c_last_name char(30),
        c_preferred_cust_flag char(1),
        c_birth_day integer,
        c_birth_month integer,
        c_birth_year integer,
        c_birth_country varchar(20),
        c_login char(13),
        c_email_address char(50),
        c_last_review_date_sk integer,
        primary key (c_customer_sk)
);
